# Generated by Django 5.0.1 on 2024-01-30 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Water',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100, verbose_name='Локация')),
                ('date', models.DateField(verbose_name='Дата доставки')),
                ('water_Liter', models.IntegerField(max_length=50, verbose_name='Сколько литров воды:')),
                ('quantity', models.IntegerField(max_length=50, verbose_name='Количество:')),
            ],
        ),
    ]
